const DB_NAME = 'visionhub-local-file-system';
const DB_VERSION = 1;
const STORE_NAME = 'handles';
const ROOT_KEY = 'root';

export const LOCAL_PROJECT_ID = 'default-project';
export const LOCAL_STORAGE_MODE = 'local';
export const ACTIVE_PROJECT_KEY = 'vh_local_active_project_id';

export const WORKSPACE_STRUCTURE = [
  { path: 'projects', description: 'Contains all local AI projects' },
  { path: 'logs', description: 'Workspace browser/system logs' },
  { path: 'trash', description: 'Workspace soft-deleted files' },
  { path: 'tmp', description: 'Workspace temporary files' },
];

export const PROJECT_STRUCTURE = [
  { path: 'images', description: 'Source images for browser labeling' },
  { path: 'labels', description: 'All labels generated by VisionHub' },
  { path: 'labels/detection', description: 'YOLO detection .txt files' },
  { path: 'labels/classification', description: 'Image-level classification labels' },
  { path: 'exports', description: 'YOLO export output' },
  { path: 'models', description: 'Model files or model registry metadata' },
  { path: 'runs', description: 'Training runs and logs' },
  { path: 'logs', description: 'Project browser/system logs' },
  { path: 'trash', description: 'Project soft-deleted files' },
  { path: 'tmp', description: 'Project temporary working files' },
];

// Kept for older UI imports. The Datasets page now renders project paths dynamically.
export const REQUIRED_STRUCTURE = PROJECT_STRUCTURE;

export function isFileSystemAccessSupported() {
  return Boolean(window.showDirectoryPicker && window.indexedDB);
}

function openDb() {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, DB_VERSION);
    req.onupgradeneeded = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(STORE_NAME)) db.createObjectStore(STORE_NAME);
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

async function idbGet(key) {
  const db = await openDb();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, 'readonly');
    const req = tx.objectStore(STORE_NAME).get(key);
    req.onsuccess = () => resolve(req.result || null);
    req.onerror = () => reject(req.error);
  });
}

async function idbSet(key, value) {
  const db = await openDb();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, 'readwrite');
    tx.objectStore(STORE_NAME).put(value, key);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
}

async function idbDelete(key) {
  const db = await openDb();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, 'readwrite');
    tx.objectStore(STORE_NAME).delete(key);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
}

export async function clearSavedRootHandle() {
  await idbDelete(ROOT_KEY);
  localStorage.removeItem('vh_local_root_name');
}

export async function getSavedRootHandle() {
  if (!isFileSystemAccessSupported()) return null;
  return idbGet(ROOT_KEY);
}

export async function saveRootHandle(handle) {
  await idbSet(ROOT_KEY, handle);
  localStorage.setItem('vh_local_root_name', handle.name || 'Local folder');
}

export async function queryRootPermission(handle) {
  if (!handle) return 'missing';
  if (!handle.queryPermission) return 'granted';
  return handle.queryPermission({ mode: 'readwrite' });
}

export async function requestRootPermission(handle) {
  if (!handle) throw new Error('No local folder handle is available.');
  let permission = await queryRootPermission(handle);
  if (permission === 'granted') return true;
  if (!handle.requestPermission) return false;
  permission = await handle.requestPermission({ mode: 'readwrite' });
  return permission === 'granted';
}

export function sanitizeProjectId(name) {
  const base = String(name || 'project')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
  return base || `project-${Date.now()}`;
}

export function getActiveLocalProjectId() {
  return localStorage.getItem(ACTIVE_PROJECT_KEY) || LOCAL_PROJECT_ID;
}

export function setActiveLocalProjectId(projectId) {
  const clean = sanitizeProjectId(projectId || LOCAL_PROJECT_ID);
  localStorage.setItem(ACTIVE_PROJECT_KEY, clean);
  localStorage.setItem('vh_project_id', clean);
  return clean;
}

async function getDirectoryByPath(rootHandle, path, create = true) {
  const parts = path.split('/').filter(Boolean);
  let dir = rootHandle;
  for (const part of parts) {
    dir = await dir.getDirectoryHandle(part, { create });
  }
  return dir;
}

async function directoryExists(rootHandle, path) {
  try {
    await getDirectoryByPath(rootHandle, path, false);
    return true;
  } catch {
    return false;
  }
}

async function fileExists(rootHandle, path) {
  try {
    const parts = path.split('/').filter(Boolean);
    const fileName = parts.pop();
    const dir = parts.length ? await getDirectoryByPath(rootHandle, parts.join('/'), false) : rootHandle;
    await dir.getFileHandle(fileName, { create: false });
    return true;
  } catch {
    return false;
  }
}

async function readTextFileFromDir(dirHandle, fileName) {
  const fileHandle = await dirHandle.getFileHandle(fileName, { create: false });
  const file = await fileHandle.getFile();
  return file.text();
}

async function writeTextFileToDir(dirHandle, fileName, text) {
  const fileHandle = await dirHandle.getFileHandle(fileName, { create: true });
  const writable = await fileHandle.createWritable();
  await writable.write(text);
  await writable.close();
}

async function readJsonFileFromDir(dirHandle, fileName, fallback = null) {
  try {
    const text = await readTextFileFromDir(dirHandle, fileName);
    return JSON.parse(text || '{}');
  } catch {
    return fallback;
  }
}

async function writeJsonFileToDir(dirHandle, fileName, value) {
  await writeTextFileToDir(dirHandle, fileName, JSON.stringify(value, null, 2));
}

export async function ensureWorkspaceStructure(rootHandle) {
  if (!rootHandle) throw new Error('No local folder selected.');
  const created = [];
  const existing = [];
  for (const item of WORKSPACE_STRUCTURE) {
    try {
      await getDirectoryByPath(rootHandle, item.path, false);
      existing.push(item.path);
    } catch {
      await getDirectoryByPath(rootHandle, item.path, true);
      created.push(item.path);
    }
  }
  return { rootName: rootHandle.name, created, existing, filesCreated: [] };
}

function defaultProjectName(rootHandle) {
  return rootHandle?.name ? `${rootHandle.name} Project` : 'Default Project';
}

async function getProjectDir(rootHandle, projectId = getActiveLocalProjectId(), create = true) {
  const safeId = sanitizeProjectId(projectId || LOCAL_PROJECT_ID);
  return getDirectoryByPath(rootHandle, `projects/${safeId}`, create);
}

export async function ensureLocalProjectStructure(rootHandle, projectId = getActiveLocalProjectId(), projectName = '') {
  if (!rootHandle) throw new Error('No local folder selected.');
  await ensureWorkspaceStructure(rootHandle);
  const safeId = sanitizeProjectId(projectId || LOCAL_PROJECT_ID);
  const projectDir = await getProjectDir(rootHandle, safeId, true);

  const created = [];
  const existing = [];
  for (const item of PROJECT_STRUCTURE) {
    try {
      await getDirectoryByPath(projectDir, item.path, false);
      existing.push(`projects/${safeId}/${item.path}`);
    } catch {
      await getDirectoryByPath(projectDir, item.path, true);
      created.push(`projects/${safeId}/${item.path}`);
    }
  }

  const filesCreated = [];
  if (!(await fileExists(projectDir, 'classes.txt'))) {
    await writeTextFileToDir(projectDir, 'classes.txt', 'OK\nNG\n');
    filesCreated.push(`projects/${safeId}/classes.txt`);
  }

  if (!(await fileExists(projectDir, 'project.json'))) {
    await writeJsonFileToDir(projectDir, 'project.json', {
      id: safeId,
      name: projectName || defaultProjectName(rootHandle),
      task_type: localStorage.getItem('vh_task') || 'Detection',
      structure_version: 2,
      created_at: new Date().toISOString(),
      note: 'Project-local images go in /images. YOLO labels are written to /labels/detection.',
    });
    filesCreated.push(`projects/${safeId}/project.json`);
  }

  return { rootName: rootHandle.name, projectId: safeId, created, existing, filesCreated };
}

export async function ensureVisionHubStructure(rootHandle) {
  const workspace = await ensureWorkspaceStructure(rootHandle);
  const projectId = getActiveLocalProjectId();
  const project = await ensureLocalProjectStructure(rootHandle, projectId, defaultProjectName(rootHandle));
  await migrateLegacyRootDataIfNeeded(rootHandle, projectId);
  return {
    rootName: rootHandle.name,
    created: [...workspace.created, ...project.created],
    existing: [...workspace.existing, ...project.existing],
    filesCreated: [...workspace.filesCreated, ...project.filesCreated],
    projectId,
  };
}

async function hasImagesInDir(dirHandle) {
  try {
    for await (const [name, handle] of dirHandle.entries()) {
      if (handle.kind === 'file' && isImageFileName(name)) return true;
    }
  } catch {
    return false;
  }
  return false;
}

async function copyFilesBetweenDirs(sourceDir, targetDir, acceptFn) {
  let copied = 0;
  for await (const [name, handle] of sourceDir.entries()) {
    if (handle.kind !== 'file' || !acceptFn(name)) continue;
    const file = await handle.getFile();
    await writeBlobToDir(targetDir, name, file);
    copied += 1;
  }
  return copied;
}

async function migrateLegacyRootDataIfNeeded(rootHandle, projectId) {
  const projectDir = await getProjectDir(rootHandle, projectId, true);
  const imagesDir = await getDirectoryByPath(projectDir, 'images', true);
  if (await hasImagesInDir(imagesDir)) return { migrated: false, copied: 0 };

  let legacyImagesDir = null;
  try {
    legacyImagesDir = await getDirectoryByPath(rootHandle, 'images', false);
  } catch {
    return { migrated: false, copied: 0 };
  }

  if (!(await hasImagesInDir(legacyImagesDir))) return { migrated: false, copied: 0 };

  const copiedImages = await copyFilesBetweenDirs(legacyImagesDir, imagesDir, isImageFileName);

  try {
    const legacyClasses = await readTextFileFromDir(rootHandle, 'classes.txt');
    await writeTextFileToDir(projectDir, 'classes.txt', legacyClasses);
  } catch {}

  try {
    const legacyLabelsDir = await getDirectoryByPath(rootHandle, 'labels/detection', false);
    const projectLabelsDir = await getDirectoryByPath(projectDir, 'labels/detection', true);
    await copyFilesBetweenDirs(legacyLabelsDir, projectLabelsDir, name => /\.txt$/i.test(name));
  } catch {}

  console.info('[local-fs] migrated legacy root images into project folder', { projectId, copiedImages });
  return { migrated: true, copied: copiedImages };
}

export async function chooseLocalRootFolder() {
  if (!isFileSystemAccessSupported()) {
    throw new Error('This browser does not support File System Access API. Use Chrome or Edge.');
  }
  const handle = await window.showDirectoryPicker({
    id: 'visionhub-local-root',
    mode: 'readwrite',
    startIn: 'documents',
  });
  const ok = await requestRootPermission(handle);
  if (!ok) throw new Error('Read/write permission was not granted for the selected folder.');
  await saveRootHandle(handle);
  if (!localStorage.getItem(ACTIVE_PROJECT_KEY)) setActiveLocalProjectId(LOCAL_PROJECT_ID);
  const structure = await ensureVisionHubStructure(handle);
  return { handle, structure };
}

export async function reconnectLocalRootFolder({ requestPermission = false } = {}) {
  const handle = await getSavedRootHandle();
  if (!handle) return null;
  const permission = requestPermission ? (await requestRootPermission(handle) ? 'granted' : 'denied') : await queryRootPermission(handle);
  if (permission !== 'granted') return { handle, permission, structure: null };
  const structure = await ensureVisionHubStructure(handle);
  return { handle, permission, structure };
}

export async function createLocalProject(rootHandle, name, taskType = localStorage.getItem('vh_task') || 'Detection') {
  if (!rootHandle) throw new Error('Select or reconnect a local folder first.');
  await ensureWorkspaceStructure(rootHandle);
  const projectsDir = await getDirectoryByPath(rootHandle, 'projects', true);
  const baseId = sanitizeProjectId(name || 'project');
  let id = baseId;
  let n = 2;
  while (true) {
    try {
      await projectsDir.getDirectoryHandle(id, { create: false });
      id = `${baseId}-${n++}`;
    } catch {
      break;
    }
  }
  await ensureLocalProjectStructure(rootHandle, id, name || id);
  const projectDir = await getProjectDir(rootHandle, id, true);
  await writeJsonFileToDir(projectDir, 'project.json', {
    id,
    name: name || id,
    task_type: taskType,
    structure_version: 2,
    created_at: new Date().toISOString(),
    note: 'Project-local images go in /images. YOLO labels are written to /labels/detection.',
  });
  setActiveLocalProjectId(id);
  return getLocalProjectSummary(rootHandle, id);
}

export async function listLocalProjects(rootHandle) {
  if (!rootHandle) return [];
  await ensureWorkspaceStructure(rootHandle);
  const projectsDir = await getDirectoryByPath(rootHandle, 'projects', true);
  const projects = [];

  for await (const [id, handle] of projectsDir.entries()) {
    if (handle.kind !== 'directory') continue;
    await ensureLocalProjectStructure(rootHandle, id, id);
    projects.push(await getLocalProjectSummary(rootHandle, id));
  }

  if (!projects.length) {
    const summary = await createLocalProject(rootHandle, defaultProjectName(rootHandle), localStorage.getItem('vh_task') || 'Detection');
    await migrateLegacyRootDataIfNeeded(rootHandle, summary.id);
    return [await getLocalProjectSummary(rootHandle, summary.id)];
  }

  projects.sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric: true, sensitivity: 'base' }));
  const activeId = getActiveLocalProjectId();
  if (!projects.some(p => p.id === activeId)) setActiveLocalProjectId(projects[0].id);
  return projects;
}

export async function readLocalClasses(rootHandle, projectId = getActiveLocalProjectId()) {
  const projectDir = await getProjectDir(rootHandle, projectId, true);
  try {
    const text = await readTextFileFromDir(projectDir, 'classes.txt');
    const classes = text.split(/\r?\n/).map(x => x.trim()).filter(Boolean);
    return classes.length ? classes : ['OK', 'NG'];
  } catch {
    await writeTextFileToDir(projectDir, 'classes.txt', 'OK\nNG\n');
    return ['OK', 'NG'];
  }
}

export async function writeLocalClasses(rootHandle, classes, projectId = getActiveLocalProjectId()) {
  const clean = classes.map(x => String(x || '').trim()).filter(Boolean);
  const unique = [];
  const seen = new Set();
  for (const name of clean) {
    const key = name.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    unique.push(name);
  }
  if (!unique.length) throw new Error('At least one class is required.');
  const projectDir = await getProjectDir(rootHandle, projectId, true);
  await writeTextFileToDir(projectDir, 'classes.txt', `${unique.join('\n')}\n`);
  return unique;
}

function isImageFileName(name) {
  return /\.(jpg|jpeg|png|bmp|webp|gif|tif|tiff)$/i.test(name);
}

function normalizeLocalFileName(name) {
  return String(name || 'image')
    .split(/[\\/]/)
    .pop()
    .replace(/[<>:"|?*\u0000-\u001F]/g, '_')
    .replace(/^\.+/, '_')
    .trim() || `image_${Date.now()}`;
}

async function writeBlobToDir(dirHandle, fileName, blob) {
  const fileHandle = await dirHandle.getFileHandle(fileName, { create: true });
  const writable = await fileHandle.createWritable();
  await writable.write(blob);
  await writable.close();
}

export async function importLocalImageFiles(rootHandle, fileList, projectId = getActiveLocalProjectId()) {
  if (!rootHandle) throw new Error('Select or reconnect a local folder first.');
  const ok = await requestRootPermission(rootHandle);
  if (!ok) throw new Error('Read/write permission was not granted for the selected folder.');
  await ensureLocalProjectStructure(rootHandle, projectId);

  const files = Array.from(fileList || []);
  const projectDir = await getProjectDir(rootHandle, projectId, true);
  const imagesDir = await getDirectoryByPath(projectDir, 'images', true);
  const result = { projectId, imported: 0, skipped: 0, overwritten: 0, files: [], skippedFiles: [] };

  for (const file of files) {
    const originalName = normalizeLocalFileName(file?.name || '');
    if (!file || !isImageFileName(originalName)) {
      result.skipped += 1;
      if (originalName) result.skippedFiles.push(originalName);
      continue;
    }

    let existed = false;
    try {
      await imagesDir.getFileHandle(originalName, { create: false });
      existed = true;
    } catch {
      existed = false;
    }

    await writeBlobToDir(imagesDir, originalName, file);
    result.imported += 1;
    if (existed) result.overwritten += 1;
    result.files.push(originalName);
  }

  return result;
}

function imageSizeFromUrl(url) {
  return new Promise(resolve => {
    const img = new Image();
    img.onload = () => resolve({ width: img.naturalWidth, height: img.naturalHeight });
    img.onerror = () => resolve({ width: null, height: null });
    img.src = url;
  });
}

export async function listLocalImages(rootHandle, projectId = getActiveLocalProjectId()) {
  await ensureLocalProjectStructure(rootHandle, projectId);
  const projectDir = await getProjectDir(rootHandle, projectId, true);
  const imagesDir = await getDirectoryByPath(projectDir, 'images', true);
  const images = [];
  for await (const [name, handle] of imagesDir.entries()) {
    if (handle.kind !== 'file' || !isImageFileName(name)) continue;
    const file = await handle.getFile();
    const url = URL.createObjectURL(file);
    const size = await imageSizeFromUrl(url);
    images.push({
      source: 'local-fs',
      projectId,
      filename: name,
      url,
      width: size.width,
      height: size.height,
      size: file.size,
      lastModified: file.lastModified,
    });
  }
  images.sort((a, b) => a.filename.localeCompare(b.filename, undefined, { numeric: true, sensitivity: 'base' }));
  return images;
}

function stemOf(filename) {
  return filename.replace(/\.[^.]+$/, '');
}

function boxId() {
  return `local-${Math.random().toString(36).slice(2, 10)}`;
}

export async function readLocalYoloBoxes(rootHandle, filename, projectId = getActiveLocalProjectId()) {
  await ensureLocalProjectStructure(rootHandle, projectId);
  const projectDir = await getProjectDir(rootHandle, projectId, true);
  const labelsDir = await getDirectoryByPath(projectDir, 'labels/detection', true);
  const labelName = `${stemOf(filename)}.txt`;
  try {
    const text = await readTextFileFromDir(labelsDir, labelName);
    return text.split(/\r?\n/).map(line => line.trim()).filter(Boolean).map(line => {
      const [class_id, x, y, w, h] = line.split(/\s+/).map(Number);
      return { id: boxId(), class_id, x, y, w, h };
    }).filter(b => Number.isFinite(b.class_id) && Number.isFinite(b.x) && Number.isFinite(b.y) && Number.isFinite(b.w) && Number.isFinite(b.h));
  } catch {
    return [];
  }
}

export async function writeLocalYoloBoxes(rootHandle, filename, boxes, projectId = getActiveLocalProjectId()) {
  await ensureLocalProjectStructure(rootHandle, projectId);
  const projectDir = await getProjectDir(rootHandle, projectId, true);
  const labelsDir = await getDirectoryByPath(projectDir, 'labels/detection', true);
  const labelName = `${stemOf(filename)}.txt`;
  const text = (boxes || []).map(b => [
    Number(b.class_id || 0),
    Number(b.x).toFixed(6),
    Number(b.y).toFixed(6),
    Number(b.w).toFixed(6),
    Number(b.h).toFixed(6),
  ].join(' ')).join('\n');
  await writeTextFileToDir(labelsDir, labelName, text ? `${text}\n` : '');
  return { projectId, labelName, count: boxes.length };
}

async function readClassificationMap(rootHandle, projectId = getActiveLocalProjectId()) {
  await ensureLocalProjectStructure(rootHandle, projectId);
  const projectDir = await getProjectDir(rootHandle, projectId, true);
  const dir = await getDirectoryByPath(projectDir, 'labels/classification', true);
  const map = await readJsonFileFromDir(dir, 'labels.json', {});
  return map && typeof map === 'object' ? map : {};
}

async function writeClassificationMap(rootHandle, map, projectId = getActiveLocalProjectId()) {
  const projectDir = await getProjectDir(rootHandle, projectId, true);
  const dir = await getDirectoryByPath(projectDir, 'labels/classification', true);
  await writeJsonFileToDir(dir, 'labels.json', map);
}

export async function readLocalClassification(rootHandle, filename, projectId = getActiveLocalProjectId()) {
  const map = await readClassificationMap(rootHandle, projectId);
  return Number.isFinite(map[filename]) ? map[filename] : null;
}

export async function writeLocalClassification(rootHandle, filename, classId, projectId = getActiveLocalProjectId()) {
  const map = await readClassificationMap(rootHandle, projectId);
  if (classId === null || classId === undefined || classId === '') delete map[filename];
  else map[filename] = Number(classId);
  await writeClassificationMap(rootHandle, map, projectId);
  return map[filename] ?? null;
}

export async function getLocalProjectSummary(rootHandle, projectId = getActiveLocalProjectId()) {
  const safeId = sanitizeProjectId(projectId || LOCAL_PROJECT_ID);
  await ensureLocalProjectStructure(rootHandle, safeId);
  const projectDir = await getProjectDir(rootHandle, safeId, true);
  const meta = await readJsonFileFromDir(projectDir, 'project.json', { id: safeId, name: safeId, task_type: localStorage.getItem('vh_task') || 'Detection' });
  const [classes, images] = await Promise.all([readLocalClasses(rootHandle, safeId), listLocalImages(rootHandle, safeId)]);
  return {
    id: safeId,
    name: meta?.name || safeId,
    task_type: meta?.task_type || localStorage.getItem('vh_task') || 'Detection',
    image_count: images.length,
    classes,
    rootName: rootHandle.name,
    path: `projects/${safeId}`,
  };
}
