const DB_NAME = 'visionhub-local-file-system';
const DB_VERSION = 1;
const STORE_NAME = 'handles';
const ROOT_KEY = 'root';

export const LOCAL_PROJECT_ID = 'local-fs';
export const LOCAL_STORAGE_MODE = 'local';

export const REQUIRED_STRUCTURE = [
  { path: 'images', description: 'Source images for browser labeling' },
  { path: 'labels', description: 'All labels generated by VisionHub' },
  { path: 'labels/detection', description: 'YOLO detection .txt files' },
  { path: 'labels/classification', description: 'Image-level classification labels' },
  { path: 'projects', description: 'Project metadata and future task configs' },
  { path: 'exports', description: 'YOLO export output' },
  { path: 'models', description: 'Model files or model registry metadata' },
  { path: 'runs', description: 'Training runs and logs' },
  { path: 'logs', description: 'Browser/system logs' },
  { path: 'trash', description: 'Soft-deleted files' },
  { path: 'tmp', description: 'Temporary working files' },
];

export function isFileSystemAccessSupported() {
  return Boolean(window.showDirectoryPicker && window.indexedDB);
}

function openDb() {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, DB_VERSION);
    req.onupgradeneeded = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(STORE_NAME)) db.createObjectStore(STORE_NAME);
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

async function idbGet(key) {
  const db = await openDb();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, 'readonly');
    const req = tx.objectStore(STORE_NAME).get(key);
    req.onsuccess = () => resolve(req.result || null);
    req.onerror = () => reject(req.error);
  });
}

async function idbSet(key, value) {
  const db = await openDb();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, 'readwrite');
    tx.objectStore(STORE_NAME).put(value, key);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
}

async function idbDelete(key) {
  const db = await openDb();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE_NAME, 'readwrite');
    tx.objectStore(STORE_NAME).delete(key);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
}

export async function clearSavedRootHandle() {
  await idbDelete(ROOT_KEY);
  localStorage.removeItem('vh_local_root_name');
}

export async function getSavedRootHandle() {
  if (!isFileSystemAccessSupported()) return null;
  return idbGet(ROOT_KEY);
}

export async function saveRootHandle(handle) {
  await idbSet(ROOT_KEY, handle);
  localStorage.setItem('vh_local_root_name', handle.name || 'Local folder');
}

export async function queryRootPermission(handle) {
  if (!handle) return 'missing';
  if (!handle.queryPermission) return 'granted';
  return handle.queryPermission({ mode: 'readwrite' });
}

export async function requestRootPermission(handle) {
  if (!handle) throw new Error('No local folder handle is available.');
  let permission = await queryRootPermission(handle);
  if (permission === 'granted') return true;
  if (!handle.requestPermission) return false;
  permission = await handle.requestPermission({ mode: 'readwrite' });
  return permission === 'granted';
}

async function getDirectoryByPath(rootHandle, path, create = true) {
  const parts = path.split('/').filter(Boolean);
  let dir = rootHandle;
  for (const part of parts) {
    dir = await dir.getDirectoryHandle(part, { create });
  }
  return dir;
}

async function fileExists(rootHandle, path) {
  try {
    const parts = path.split('/').filter(Boolean);
    const fileName = parts.pop();
    const dir = parts.length ? await getDirectoryByPath(rootHandle, parts.join('/'), false) : rootHandle;
    await dir.getFileHandle(fileName, { create: false });
    return true;
  } catch {
    return false;
  }
}

async function readTextFileFromDir(dirHandle, fileName) {
  const fileHandle = await dirHandle.getFileHandle(fileName, { create: false });
  const file = await fileHandle.getFile();
  return file.text();
}

async function writeTextFileToDir(dirHandle, fileName, text) {
  const fileHandle = await dirHandle.getFileHandle(fileName, { create: true });
  const writable = await fileHandle.createWritable();
  await writable.write(text);
  await writable.close();
}

export async function ensureVisionHubStructure(rootHandle) {
  if (!rootHandle) throw new Error('No local folder selected.');
  const created = [];
  const existing = [];
  for (const item of REQUIRED_STRUCTURE) {
    try {
      await getDirectoryByPath(rootHandle, item.path, false);
      existing.push(item.path);
    } catch {
      await getDirectoryByPath(rootHandle, item.path, true);
      created.push(item.path);
    }
  }

  const filesCreated = [];
  if (!(await fileExists(rootHandle, 'classes.txt'))) {
    await writeTextFileToDir(rootHandle, 'classes.txt', 'OK\nNG\n');
    filesCreated.push('classes.txt');
  }
  if (!(await fileExists(rootHandle, 'project.json'))) {
    await writeTextFileToDir(rootHandle, 'project.json', JSON.stringify({
      name: rootHandle.name || 'VisionHub Local Project',
      task_type: 'Detection',
      structure_version: 1,
      created_at: new Date().toISOString(),
      note: 'Images go in /images. YOLO labels are written to /labels/detection.',
    }, null, 2));
    filesCreated.push('project.json');
  }
  return { rootName: rootHandle.name, created, existing, filesCreated };
}

export async function chooseLocalRootFolder() {
  if (!isFileSystemAccessSupported()) {
    throw new Error('This browser does not support File System Access API. Use Chrome or Edge.');
  }
  const handle = await window.showDirectoryPicker({
    id: 'visionhub-local-root',
    mode: 'readwrite',
    startIn: 'documents',
  });
  const ok = await requestRootPermission(handle);
  if (!ok) throw new Error('Read/write permission was not granted for the selected folder.');
  await saveRootHandle(handle);
  const structure = await ensureVisionHubStructure(handle);
  return { handle, structure };
}

export async function reconnectLocalRootFolder({ requestPermission = false } = {}) {
  const handle = await getSavedRootHandle();
  if (!handle) return null;
  const permission = requestPermission ? (await requestRootPermission(handle) ? 'granted' : 'denied') : await queryRootPermission(handle);
  if (permission !== 'granted') return { handle, permission, structure: null };
  const structure = await ensureVisionHubStructure(handle);
  return { handle, permission, structure };
}

export async function readLocalClasses(rootHandle) {
  try {
    const text = await readTextFileFromDir(rootHandle, 'classes.txt');
    const classes = text.split(/\r?\n/).map(x => x.trim()).filter(Boolean);
    return classes.length ? classes : ['OK', 'NG'];
  } catch {
    await writeTextFileToDir(rootHandle, 'classes.txt', 'OK\nNG\n');
    return ['OK', 'NG'];
  }
}

export async function writeLocalClasses(rootHandle, classes) {
  const clean = classes.map(x => String(x || '').trim()).filter(Boolean);
  await writeTextFileToDir(rootHandle, 'classes.txt', `${clean.join('\n')}\n`);
  return clean;
}

function isImageFileName(name) {
  return /\.(jpg|jpeg|png|bmp|webp|gif|tif|tiff)$/i.test(name);
}

function normalizeLocalFileName(name) {
  return String(name || 'image')
    .split(/[\\/]/)
    .pop()
    .replace(/[<>:"|?*\u0000-\u001F]/g, '_')
    .replace(/^\.+/, '_')
    .trim() || `image_${Date.now()}`;
}

async function writeBlobToDir(dirHandle, fileName, blob) {
  const fileHandle = await dirHandle.getFileHandle(fileName, { create: true });
  const writable = await fileHandle.createWritable();
  await writable.write(blob);
  await writable.close();
}

export async function importLocalImageFiles(rootHandle, fileList) {
  if (!rootHandle) throw new Error('Select or reconnect a local folder first.');
  const ok = await requestRootPermission(rootHandle);
  if (!ok) throw new Error('Read/write permission was not granted for the selected folder.');
  await ensureVisionHubStructure(rootHandle);

  const files = Array.from(fileList || []);
  const imagesDir = await getDirectoryByPath(rootHandle, 'images', true);
  const result = { imported: 0, skipped: 0, overwritten: 0, files: [], skippedFiles: [] };

  for (const file of files) {
    const originalName = normalizeLocalFileName(file?.name || '');
    if (!file || !isImageFileName(originalName)) {
      result.skipped += 1;
      if (originalName) result.skippedFiles.push(originalName);
      continue;
    }

    let existed = false;
    try {
      await imagesDir.getFileHandle(originalName, { create: false });
      existed = true;
    } catch {
      existed = false;
    }

    await writeBlobToDir(imagesDir, originalName, file);
    result.imported += 1;
    if (existed) result.overwritten += 1;
    result.files.push(originalName);
  }

  return result;
}

function imageSizeFromUrl(url) {
  return new Promise(resolve => {
    const img = new Image();
    img.onload = () => resolve({ width: img.naturalWidth, height: img.naturalHeight });
    img.onerror = () => resolve({ width: null, height: null });
    img.src = url;
  });
}

export async function listLocalImages(rootHandle) {
  const imagesDir = await getDirectoryByPath(rootHandle, 'images', true);
  const images = [];
  for await (const [name, handle] of imagesDir.entries()) {
    if (handle.kind !== 'file' || !isImageFileName(name)) continue;
    const file = await handle.getFile();
    const url = URL.createObjectURL(file);
    const size = await imageSizeFromUrl(url);
    images.push({
      source: 'local-fs',
      filename: name,
      url,
      width: size.width,
      height: size.height,
      size: file.size,
      lastModified: file.lastModified,
    });
  }
  images.sort((a, b) => a.filename.localeCompare(b.filename, undefined, { numeric: true, sensitivity: 'base' }));
  return images;
}

function stemOf(filename) {
  return filename.replace(/\.[^.]+$/, '');
}

function boxId() {
  return `local-${Math.random().toString(36).slice(2, 10)}`;
}

export async function readLocalYoloBoxes(rootHandle, filename) {
  const labelsDir = await getDirectoryByPath(rootHandle, 'labels/detection', true);
  const labelName = `${stemOf(filename)}.txt`;
  try {
    const text = await readTextFileFromDir(labelsDir, labelName);
    return text.split(/\r?\n/).map(line => line.trim()).filter(Boolean).map(line => {
      const [class_id, x, y, w, h] = line.split(/\s+/).map(Number);
      return { id: boxId(), class_id, x, y, w, h };
    }).filter(b => Number.isFinite(b.class_id) && Number.isFinite(b.x) && Number.isFinite(b.y) && Number.isFinite(b.w) && Number.isFinite(b.h));
  } catch {
    return [];
  }
}

export async function writeLocalYoloBoxes(rootHandle, filename, boxes) {
  const labelsDir = await getDirectoryByPath(rootHandle, 'labels/detection', true);
  const labelName = `${stemOf(filename)}.txt`;
  const text = (boxes || []).map(b => [
    Number(b.class_id || 0),
    Number(b.x).toFixed(6),
    Number(b.y).toFixed(6),
    Number(b.w).toFixed(6),
    Number(b.h).toFixed(6),
  ].join(' ')).join('\n');
  await writeTextFileToDir(labelsDir, labelName, text ? `${text}\n` : '');
  return { labelName, count: boxes.length };
}

async function readClassificationMap(rootHandle) {
  const dir = await getDirectoryByPath(rootHandle, 'labels/classification', true);
  try {
    const text = await readTextFileFromDir(dir, 'labels.json');
    return JSON.parse(text || '{}');
  } catch {
    return {};
  }
}

async function writeClassificationMap(rootHandle, map) {
  const dir = await getDirectoryByPath(rootHandle, 'labels/classification', true);
  await writeTextFileToDir(dir, 'labels.json', JSON.stringify(map, null, 2));
}

export async function readLocalClassification(rootHandle, filename) {
  const map = await readClassificationMap(rootHandle);
  return Number.isFinite(map[filename]) ? map[filename] : null;
}

export async function writeLocalClassification(rootHandle, filename, classId) {
  const map = await readClassificationMap(rootHandle);
  if (classId === null || classId === undefined || classId === '') delete map[filename];
  else map[filename] = Number(classId);
  await writeClassificationMap(rootHandle, map);
  return map[filename] ?? null;
}

export async function getLocalProjectSummary(rootHandle) {
  const [classes, images] = await Promise.all([readLocalClasses(rootHandle), listLocalImages(rootHandle)]);
  return {
    id: LOCAL_PROJECT_ID,
    name: `Local PC: ${rootHandle.name}`,
    task_type: localStorage.getItem('vh_task') || 'Detection',
    image_count: images.length,
    classes,
    rootName: rootHandle.name,
  };
}
